const data = {
  quadbikes: {
    quadbike1: {
      type: "Квадроцикл",
      name: "Quadbike 1",
      price: "1049500",
      drive: "front",
      availability: "true",
      power: "110",
      country: "USA",
    },
    quadbike2: {
      type: "Квадроцикл",
      name: "Quadbike 2",
      price: "857666",
      drive: "rear",
      availability: "true",
      power: "91",
      country: "Russia",
    },
    quadbike3: {
      type: "Квадроцикл",
      name: "Quadbike 3",
      price: "732345",
      drive: "all",
      availability: "true",
      power: "141",
      country: "China",
    },
    quadbike4: {
      type: "Квадроцикл",
      name: "Quadbike 4",
      price: "1503150",
      drive: "front",
      availability: "true",
      power: "200",
      country: "Germany",
    },
    quadbike5: {
      type: "Квадроцикл",
      name: "Quadbike 5",
      price: "505555",
      drive: "rear",
      availability: "true",
      power: "121",
      country: "China",
    },
    quadbike6: {
      type: "Квадроцикл",
      name: "Quadbike 6",
      price: "770000",
      drive: "all",
      availability: "true",
      power: "200",
      country: "USA",
    },
    quadbike7: {
      type: "Квадроцикл",
      name: "Quadbike 7",
      price: "1800000",
      drive: "all",
      availability: "true",
      power: "257",
      country: "Germany",
    },
    quadbike8: {
      type: "Квадроцикл",
      name: "Quadbike 8",
      price: "960755",
      drive: "all",
      availability: "true",
      power: "170",
      country: "Russia",
    },
    quadbike9: {
      type: "Квадроцикл",
      name: "Quadbike 9",
      price: "1666666",
      drive: "rear",
      availability: "true",
      power: "235",
      country: "Germany",
    },
    quadbike10: {
      type: "Квадроцикл",
      name: "Quadbike 10",
      price: "120753",
      drive: "front",
      availability: "true",
      power: "167",
      country: "China",
    },
    quadbike11: {
      type: "Квадроцикл",
      name: "Quadbike 11",
      price: "460798",
      drive: "rear",
      availability: "true",
      power: "85",
      country: "Russia",
    },
    quadbike12: {
      type: "Квадроцикл",
      name: "Quadbike 12",
      price: "1999999",
      drive: "all",
      availability: "true",
      power: "300",
      country: "Germany",
    },
  },
  //-------------------------------------------------------------------------------
  //---------------------Launch----------------------------------------------------
  launch: {
    launch1: {
      type: "Катер",
      name: "Launch 1",
      price: "1049500",
      drive: "front",
      availability: "true",
      power: "110",
      country: "USA",
    },
    launch2: {
      type: "Катер",
      name: "Launch 2",
      price: "857666",
      drive: "rear",
      availability: "true",
      power: "91",
      country: "Russia",
    },
    launch3: {
      type: "Катер",
      name: "Launch 3",
      price: "732345",
      drive: "all",
      availability: "true",
      power: "141",
      country: "China",
    },
    launch4: {
      type: "Катер",
      name: "Launch 4",
      price: "1503150",
      drive: "front",
      availability: "true",
      power: "200",
      country: "Germany",
    },
    launch5: {
      type: "Катер",
      name: "Launch 5",
      price: "505555",
      drive: "rear",
      availability: "true",
      power: "121",
      country: "China",
    },
    launch6: {
      type: "Катер",
      name: "Launch 6",
      price: "770000",
      drive: "all",
      availability: "true",
      power: "200",
      country: "USA",
    },
    launch7: {
      type: "Катер",
      name: "Launch 7",
      price: "1800000",
      drive: "all",
      availability: "true",
      power: "257",
      country: "Germany",
    },
    launch8: {
      type: "Катер",
      name: "Launch 8",
      price: "960755",
      drive: "all",
      availability: "true",
      power: "170",
      country: "Russia",
    },
    launch9: {
      type: "Катер",
      name: "Launch 9",
      price: "1666666",
      drive: "rear",
      availability: "true",
      power: "235",
      country: "Germany",
    },
    launch10: {
      type: "Катер",
      name: "Launch 10",
      price: "120753",
      drive: "front",
      availability: "true",
      power: "167",
      country: "China",
    },
    launch11: {
      type: "Катер",
      name: "Launch 11",
      price: "460798",
      drive: "rear",
      availability: "true",
      power: "85",
      country: "Russia",
    },
    launch12: {
      type: "Катер",
      name: "Launch 12",
      price: "1999999",
      drive: "all",
      availability: "true",
      power: "300",
      country: "Germany",
    },
  },
  //-------------------------------------------------------------------------------
  //---------------------Jetskis---------------------------------------------------
  jetskis: {
    jetski1: {
      type: "Гидроцикл",
      name: "BRP SeaDoo GTI 130hp",
      price: "1049500",
      drive: "front",
      availability: "true",
      power: "110",
      country: "USA",
    },
    jetski2: {
      type: "Гидроцикл",
      name: "Spark 2-UP 900 Ho",
      price: "857666",
      drive: "rear",
      availability: "true",
      power: "91",
      country: "Russia",
    },
    jetski3: {
      type: "Гидроцикл",
      name: "BRP SeaDoo GTX 300hp",
      price: "732345",
      drive: "all",
      availability: "true",
      power: "141",
      country: "China",
    },
    jetski4: {
      type: "Гидроцикл",
      name: "BRP SeaDoo WAKE 230hp PRO",
      price: "1503150",
      drive: "front",
      availability: "true",
      power: "200",
      country: "Germany",
    },
    jetski5: {
      type: "Гидроцикл",
      name: "Spark 2-UP 700",
      price: "505555",
      drive: "rear",
      availability: "true",
      power: "121",
      country: "China",
    },
    jetski6: {
      type: "Гидроцикл",
      name: "BPR Scoobie-Doo 228",
      price: "770000",
      drive: "all",
      availability: "true",
      power: "200",
      country: "USA",
    },
    jetski7: {
      type: "Гидроцикл",
      name: "RGD Eshkere 1330",
      price: "1800000",
      drive: "all",
      availability: "true",
      power: "257",
      country: "Germany",
    },
    jetski8: {
      type: "Гидроцикл",
      name: "BRP SeaDoo Spark 60hp",
      price: "960755",
      drive: "all",
      availability: "true",
      power: "170",
      country: "Russia",
    },
    jetski9: {
      type: "Гидроцикл",
      name: "PGD Scoobie-Doo 1400",
      price: "1666666",
      drive: "rear",
      availability: "true",
      power: "235",
      country: "Germany",
    },
    jetski10: {
      type: "Гидроцикл",
      name: "BRP SeaDoo GTR 300hp",
      price: "120753",
      drive: "front",
      availability: "true",
      power: "167",
      country: "China",
    },
    jetski11: {
      type: "Гидроцикл",
      name: "BRP SeaDoo GTI 155hp",
      price: "460798",
      drive: "rear",
      availability: "true",
      power: "85",
      country: "Russia",
    },
    jetski12: {
      type: "Гидроцикл",
      name: "FBI SeaDoo GTX 666hp",
      price: "1999999",
      drive: "all",
      availability: "true",
      power: "300",
      country: "Germany",
    },
  },
  //----------------------------------------------------------------------------
  //----------------------Boats-------------------------------------------------
  //Sorry for this useless information i dont know how to generate it dynamically or shorten the code
  boats: {
    boat1: {
      type: "Лодка",
      name: "Boat 1",
      price: "1049500",
      drive: "front",
      availability: "true",
      power: "110",
      country: "USA",
    },
    boat2: {
      type: "Лодка",
      name: "Boat 2",
      price: "857666",
      drive: "rear",
      availability: "true",
      power: "91",
      country: "Russia",
    },
    boat3: {
      type: "Лодка",
      name: "Boat 3",
      price: "732345",
      drive: "all",
      availability: "true",
      power: "141",
      country: "China",
    },
    boat4: {
      type: "Лодка",
      name: "Boat 4",
      price: "1503150",
      drive: "front",
      availability: "true",
      power: "200",
      country: "Germany",
    },
    boat5: {
      type: "Лодка",
      name: "Boat 5",
      price: "505555",
      drive: "rear",
      availability: "true",
      power: "121",
      country: "China",
    },
    boat6: {
      type: "Лодка",
      name: "Boat 6",
      price: "770000",
      drive: "all",
      availability: "true",
      power: "200",
      country: "USA",
    },
    boat7: {
      type: "Лодка",
      name: "Boat 7",
      price: "1800000",
      drive: "all",
      availability: "true",
      power: "257",
      country: "Germany",
    },
    boat8: {
      type: "Лодка",
      name: "Boat 8",
      price: "960755",
      drive: "all",
      availability: "true",
      power: "170",
      country: "Russia",
    },
    boat9: {
      type: "Лодка",
      name: "Boat 9",
      price: "1666666",
      drive: "rear",
      availability: "true",
      power: "235",
      country: "Germany",
    },
    boat10: {
      type: "Лодка",
      name: "Boat 10",
      price: "120753",
      drive: "front",
      availability: "true",
      power: "167",
      country: "China",
    },
    boat11: {
      type: "Лодка",
      name: "Boat 11",
      price: "460798",
      drive: "rear",
      availability: "true",
      power: "85",
      country: "Russia",
    },
    boat12: {
      type: "Лодка",
      name: "Boat 12",
      price: "1999999",
      drive: "all",
      availability: "true",
      power: "300",
      country: "Germany",
    },
  },
  //--------------------------------------------------------------------

  //-------------------All Terrain Vehicles-----------------------------
  vehicles: {
    vehicle1: {
      type: "Вездеход",
      name: "Vehicle 1",
      price: "1049500",
      drive: "front",
      availability: "true",
      power: "110",
      country: "USA",
    },
    vehicle2: {
      type: "Вездеход",
      name: "Vehicle 2",
      price: "857666",
      drive: "rear",
      availability: "true",
      power: "91",
      country: "Russia",
    },
    vehicle3: {
      type: "Вездеход",
      name: "Vehicle 3",
      price: "732345",
      drive: "all",
      availability: "true",
      power: "141",
      country: "China",
    },
    vehicle4: {
      type: "Вездеход",
      name: "Vehicle 4",
      price: "1503150",
      drive: "front",
      availability: "true",
      power: "200",
      country: "Germany",
    },
    vehicle5: {
      type: "Вездеход",
      name: "Vehicle 5",
      price: "505555",
      drive: "rear",
      availability: "true",
      power: "121",
      country: "China",
    },
    vehicle6: {
      type: "Вездеход",
      name: "Vehicle 6",
      price: "770000",
      drive: "all",
      availability: "true",
      power: "200",
      country: "USA",
    },
    vehicle7: {
      type: "Вездеход",
      name: "Vehicle 7",
      price: "1800000",
      drive: "all",
      availability: "true",
      power: "257",
      country: "Germany",
    },
    vehicle8: {
      type: "Вездеход",
      name: "Vehicle 8",
      price: "960755",
      drive: "all",
      availability: "true",
      power: "170",
      country: "Russia",
    },
    vehicle9: {
      type: "Вездеход",
      name: "Vehicle 9",
      price: "1666666",
      drive: "rear",
      availability: "true",
      power: "235",
      country: "Germany",
    },
    vehicle10: {
      type: "Вездеход",
      name: "Vehicle 10",
      price: "120753",
      drive: "front",
      availability: "true",
      power: "167",
      country: "China",
    },
    vehicle11: {
      type: "Вездеход",
      name: "Vehicle 11",
      price: "460798",
      drive: "rear",
      availability: "true",
      power: "85",
      country: "Russia",
    },
    vehicle12: {
      type: "Вездеход",
      name: "Vehicle 12",
      price: "1999999",
      drive: "all",
      availability: "true",
      power: "300",
      country: "Germany",
    },
  },
  snowmobiles: {
    snowmobile1: {
      type: "Снегоход",
      name: "Snowmobile 1",
      price: "1049500",
      drive: "front",
      availability: "true",
      power: "110",
      country: "USA",
    },
    snowmobile2: {
      type: "Снегоход",
      name: "Snowmobile 2",
      price: "857666",
      drive: "rear",
      availability: "true",
      power: "91",
      country: "Russia",
    },
    snowmobile3: {
      type: "Снегоход",
      name: "Snowmobile 3",
      price: "732345",
      drive: "all",
      availability: "true",
      power: "141",
      country: "China",
    },
    snowmobile4: {
      type: "Снегоход",
      name: "Snowmobile 4",
      price: "1503150",
      drive: "front",
      availability: "true",
      power: "200",
      country: "Germany",
    },
    snowmobile5: {
      type: "Снегоход",
      name: "Snowmobile 5",
      price: "505555",
      drive: "rear",
      availability: "true",
      power: "121",
      country: "China",
    },
    snowmobile6: {
      type: "Снегоход",
      name: "Snowmobile 6",
      price: "770000",
      drive: "all",
      availability: "true",
      power: "200",
      country: "USA",
    },
    snowmobile7: {
      type: "Снегоход",
      name: "Snowmobile 7",
      price: "1800000",
      drive: "all",
      availability: "true",
      power: "257",
      country: "Germany",
    },
    snowmobile8: {
      type: "Снегоход",
      name: "Snowmobile 8",
      price: "960755",
      drive: "all",
      availability: "true",
      power: "170",
      country: "Russia",
    },
    snowmobile9: {
      type: "Снегоход",
      name: "Snowmobile 9",
      price: "1666666",
      drive: "rear",
      availability: "true",
      power: "235",
      country: "Germany",
    },
    snowmobile10: {
      type: "Снегоход",
      name: "Snowmobile 10",
      price: "120753",
      drive: "front",
      availability: "true",
      power: "167",
      country: "China",
    },
    snowmobile11: {
      type: "Снегоход",
      name: "Snowmobile 11",
      price: "460798",
      drive: "rear",
      availability: "true",
      power: "85",
      country: "Russia",
    },
    snowmobile12: {
      type: "Снегоход",
      name: "Snowmobile 12",
      price: "1999999",
      drive: "all",
      availability: "true",
      power: "300",
      country: "Germany",
    },
  },
  engines: {
    engine1: {
      type: "Двигатель",
      name: "Engine 1",
      price: "1049500",
      drive: "front",
      availability: "true",
      power: "110",
      country: "USA",
    },
    engine2: {
      type: "Двигатель",
      name: "Engine 2",
      price: "857666",
      drive: "rear",
      availability: "true",
      power: "91",
      country: "Russia",
    },
    engine3: {
      type: "Двигатель",
      name: "Engine 3",
      price: "732345",
      drive: "all",
      availability: "true",
      power: "141",
      country: "China",
    },
    engine4: {
      type: "Двигатель",
      name: "Engine 4",
      price: "1503150",
      drive: "front",
      availability: "true",
      power: "200",
      country: "Germany",
    },
    engine5: {
      type: "Двигатель",
      name: "Engine 5",
      price: "505555",
      drive: "rear",
      availability: "true",
      power: "121",
      country: "China",
    },
    engine6: {
      type: "Двигатель",
      name: "Engine 6",
      price: "770000",
      drive: "all",
      availability: "true",
      power: "200",
      country: "USA",
    },
    engine7: {
      type: "Двигатель",
      name: "Engine 7",
      price: "1800000",
      drive: "all",
      availability: "true",
      power: "257",
      country: "Germany",
    },
    engine8: {
      type: "Двигатель",
      name: "Engine 8",
      price: "960755",
      drive: "all",
      availability: "true",
      power: "170",
      country: "Russia",
    },
    engine9: {
      type: "Двигатель",
      name: "Engine 9",
      price: "1666666",
      drive: "rear",
      availability: "true",
      power: "235",
      country: "Germany",
    },
    engine10: {
      type: "Двигатель",
      name: "Engine 10",
      price: "120753",
      drive: "front",
      availability: "true",
      power: "167",
      country: "China",
    },
    engine11: {
      type: "Двигатель",
      name: "Engine 11",
      price: "460798",
      drive: "rear",
      availability: "true",
      power: "85",
      country: "Russia",
    },
    engine12: {
      type: "Двигатель",
      name: "Engine 12",
      price: "1999999",
      drive: "all",
      availability: "true",
      power: "300",
      country: "Germany",
    },
  },
  spares: {
    spare1: {
      type: "Запчасть",
      name: "Spare 1",
      price: "1049500",
      drive: "front",
      availability: "true",
      power: "110",
      country: "USA",
    },
    spare2: {
      type: "Запчасть",
      name: "Spare 2",
      price: "857666",
      drive: "rear",
      availability: "true",
      power: "91",
      country: "Russia",
    },
    spare3: {
      type: "Запчасть",
      name: "Spare 3",
      price: "732345",
      drive: "all",
      availability: "true",
      power: "141",
      country: "China",
    },
    spare4: {
      type: "Запчасть",
      name: "Spare 4",
      price: "1503150",
      drive: "front",
      availability: "true",
      power: "200",
      country: "Germany",
    },
    spare5: {
      type: "Запчасть",
      name: "Spare 5",
      price: "505555",
      drive: "rear",
      availability: "true",
      power: "121",
      country: "China",
    },
    spare6: {
      type: "Запчасть",
      name: "Spare 6",
      price: "770000",
      drive: "all",
      availability: "true",
      power: "200",
      country: "USA",
    },
    spare7: {
      type: "Запчасть",
      name: "Spare 7",
      price: "1800000",
      drive: "all",
      availability: "true",
      power: "257",
      country: "Germany",
    },
    spare8: {
      type: "Запчасть",
      name: "Spare 8",
      price: "960755",
      drive: "all",
      availability: "true",
      power: "170",
      country: "Russia",
    },
    spare9: {
      type: "Запчасть",
      name: "Spare 9",
      price: "1666666",
      drive: "rear",
      availability: "true",
      power: "235",
      country: "Germany",
    },
    spare10: {
      type: "Запчасть",
      name: "Spare 10",
      price: "120753",
      drive: "front",
      availability: "true",
      power: "167",
      country: "China",
    },
    spare11: {
      type: "Запчасть",
      name: "Spare 11",
      price: "460798",
      drive: "rear",
      availability: "true",
      power: "85",
      country: "Russia",
    },
    spare12: {
      type: "Запчасть",
      name: "Spare 12",
      price: "1999999",
      drive: "all",
      availability: "true",
      power: "300",
      country: "Germany",
    },
  },
};

export { data };
