const quadbikes = {
  quadbike1: {
    name: "Quadbike 1",
    price: "1049500",
    drive: "front",
    availability: "true",
    power: "110",
    country: "USA",
  },
  quadbike2: {
    name: "Quadbike 2",
    price: "857666",
    drive: "rear",
    availability: "true",
    power: "91",
    country: "Russia",
  },
  quadbike3: {
    name: "Quadbike 3",
    price: "732345",
    drive: "all",
    availability: "true",
    power: "141",
    country: "China",
  },
  quadbike4: {
    name: "Quadbike 4",
    price: "1503150",
    drive: "front",
    availability: "true",
    power: "200",
    country: "Germany",
  },
  quadbike5: {
    name: "Quadbike 5",
    price: "505555",
    drive: "rear",
    availability: "true",
    power: "121",
    country: "China",
  },
  quadbike6: {
    name: "Quadbike 6",
    price: "770000",
    drive: "all",
    availability: "true",
    power: "200",
    country: "USA",
  },
  quadbike7: {
    name: "Quadbike 7",
    price: "1800000",
    drive: "all",
    availability: "true",
    power: "257",
    country: "Germany",
  },
  quadbike8: {
    name: "Quadbike 8",
    price: "960755",
    drive: "all",
    availability: "true",
    power: "170",
    country: "Russia",
  },
  quadbike9: {
    name: "Quadbike 9",
    price: "1666666",
    drive: "rear",
    availability: "true",
    power: "235",
    country: "Germany",
  },
  quadbike10: {
    name: "Quadbike 10",
    price: "120753",
    drive: "front",
    availability: "true",
    power: "167",
    country: "China",
  },
  quadbike11: {
    name: "Quadbike 11",
    price: "460798",
    drive: "rear",
    availability: "true",
    power: "85",
    country: "Russia",
  },
  quadbike12: {
    name: "Quadbike 12",
    price: "1999999",
    drive: "all",
    availability: "true",
    power: "300",
    country: "Germany",
  },
};
//-------------------------------------------------------------------------------
//---------------------Launch----------------------------------------------------
const launch = {
  launch1: {
    name: "Launch 1",
    price: "1049500",
    drive: "front",
    availability: "true",
    power: "110",
    country: "USA",
  },
  launch2: {
    name: "Launch 2",
    price: "857666",
    drive: "rear",
    availability: "true",
    power: "91",
    country: "Russia",
  },
  launch3: {
    name: "Launch 3",
    price: "732345",
    drive: "all",
    availability: "true",
    power: "141",
    country: "China",
  },
  launch4: {
    name: "Launch 4",
    price: "1503150",
    drive: "front",
    availability: "true",
    power: "200",
    country: "Germany",
  },
  launch5: {
    name: "Launch 5",
    price: "505555",
    drive: "rear",
    availability: "true",
    power: "121",
    country: "China",
  },
  launch6: {
    name: "Launch 6",
    price: "770000",
    drive: "all",
    availability: "true",
    power: "200",
    country: "USA",
  },
  launch7: {
    name: "Launch 7",
    price: "1800000",
    drive: "all",
    availability: "true",
    power: "257",
    country: "Germany",
  },
  launch8: {
    name: "Launch 8",
    price: "960755",
    drive: "all",
    availability: "true",
    power: "170",
    country: "Russia",
  },
  launch9: {
    name: "Launch 9",
    price: "1666666",
    drive: "rear",
    availability: "true",
    power: "235",
    country: "Germany",
  },
  launch10: {
    name: "Launch 10",
    price: "120753",
    drive: "front",
    availability: "true",
    power: "167",
    country: "China",
  },
  launch11: {
    name: "Launch 11",
    price: "460798",
    drive: "rear",
    availability: "true",
    power: "85",
    country: "Russia",
  },
  launch12: {
    name: "Launch 12",
    price: "1999999",
    drive: "all",
    availability: "true",
    power: "300",
    country: "Germany",
  },
};
//-------------------------------------------------------------------------------
//---------------------Jetskis---------------------------------------------------
const jetskis = {
  jetski1: {
    name: "BRP SeaDoo GTI 130hp",
    price: "1049500",
    drive: "front",
    availability: "true",
    power: "110",
    country: "USA",
  },
  jetski2: {
    name: "Spark 2-UP 900 Ho",
    price: "857666",
    drive: "rear",
    availability: "true",
    power: "91",
    country: "Russia",
  },
  jetski3: {
    name: "BRP SeaDoo GTX 300hp",
    price: "732345",
    drive: "all",
    availability: "true",
    power: "141",
    country: "China",
  },
  jetski4: {
    name: "BRP SeaDoo WAKE 230hp PRO",
    price: "1503150",
    drive: "front",
    availability: "true",
    power: "200",
    country: "Germany",
  },
  jetski5: {
    name: "Spark 2-UP 700",
    price: "505555",
    drive: "rear",
    availability: "true",
    power: "121",
    country: "China",
  },
  jetski6: {
    name: "BPR Scoobie-Doo 228",
    price: "770000",
    drive: "all",
    availability: "true",
    power: "200",
    country: "USA",
  },
  jetski7: {
    name: "RGD Eshkere 1330",
    price: "1800000",
    drive: "all",
    availability: "true",
    power: "257",
    country: "Germany",
  },
  jetski8: {
    name: "BRP SeaDoo Spark 60hp",
    price: "960755",
    drive: "all",
    availability: "true",
    power: "170",
    country: "Russia",
  },
  jetski9: {
    name: "PGD Scoobie-Doo 1400",
    price: "1666666",
    drive: "rear",
    availability: "true",
    power: "235",
    country: "Germany",
  },
  jetski10: {
    name: "BRP SeaDoo GTR 300hp",
    price: "120753",
    drive: "front",
    availability: "true",
    power: "167",
    country: "China",
  },
  jetski11: {
    name: "BRP SeaDoo GTI 155hp",
    price: "460798",
    drive: "rear",
    availability: "true",
    power: "85",
    country: "Russia",
  },
  jetski12: {
    name: "FBI SeaDoo GTX 666hp",
    price: "1999999",
    drive: "all",
    availability: "true",
    power: "300",
    country: "Germany",
  },
};
//----------------------------------------------------------------------------
//----------------------Boats-------------------------------------------------
//Sorry for this useless information i dont know how to generate it dynamically or shorten the code
const boats = {
  boat1: {
    name: "Boat 1",
    price: "1049500",
    drive: "front",
    availability: "true",
    power: "110",
    country: "USA",
  },
  boat2: {
    name: "Boat 2",
    price: "857666",
    drive: "rear",
    availability: "true",
    power: "91",
    country: "Russia",
  },
  boat3: {
    name: "Boat 3",
    price: "732345",
    drive: "all",
    availability: "true",
    power: "141",
    country: "China",
  },
  boat4: {
    name: "Boat 4",
    price: "1503150",
    drive: "front",
    availability: "true",
    power: "200",
    country: "Germany",
  },
  boat5: {
    name: "Boat 5",
    price: "505555",
    drive: "rear",
    availability: "true",
    power: "121",
    country: "China",
  },
  boat6: {
    name: "Boat 6 ",
    price: "770000",
    drive: "all",
    availability: "true",
    power: "200",
    country: "USA",
  },
  boat7: {
    name: "Boat 7",
    price: "1800000",
    drive: "all",
    availability: "true",
    power: "257",
    country: "Germany",
  },
  boat8: {
    name: "Boat 8",
    price: "960755",
    drive: "all",
    availability: "true",
    power: "170",
    country: "Russia",
  },
  boat9: {
    name: "Boat 9",
    price: "1666666",
    drive: "rear",
    availability: "true",
    power: "235",
    country: "Germany",
  },
  boat10: {
    name: "Boat 10",
    price: "120753",
    drive: "front",
    availability: "true",
    power: "167",
    country: "China",
  },
  boat11: {
    name: "Boat 11",
    price: "460798",
    drive: "rear",
    availability: "true",
    power: "85",
    country: "Russia",
  },
  boat12: {
    name: "Boat 12",
    price: "1999999",
    drive: "all",
    availability: "true",
    power: "300",
    country: "Germany",
  },
};
//--------------------------------------------------------------------

//-------------------All Terrain Vehicles-----------------------------
const vehicles = {
  vehicle1: {
    name: "Vehicle 1",
    price: "1049500",
    drive: "front",
    availability: "true",
    power: "110",
    country: "USA",
  },
  vehicle2: {
    name: "Vehicle 2",
    price: "857666",
    drive: "rear",
    availability: "true",
    power: "91",
    country: "Russia",
  },
  vehicle3: {
    name: "Vehicle 3",
    price: "732345",
    drive: "all",
    availability: "true",
    power: "141",
    country: "China",
  },
  vehicle4: {
    name: "Vehicle 4",
    price: "1503150",
    drive: "front",
    availability: "true",
    power: "200",
    country: "Germany",
  },
  vehicle5: {
    name: "Vehicle 5",
    price: "505555",
    drive: "rear",
    availability: "true",
    power: "121",
    country: "China",
  },
  vehicle6: {
    name: "Vehicle 6",
    price: "770000",
    drive: "all",
    availability: "true",
    power: "200",
    country: "USA",
  },
  vehicle7: {
    name: "Vehicle 7",
    price: "1800000",
    drive: "all",
    availability: "true",
    power: "257",
    country: "Germany",
  },
  vehicle8: {
    name: "Vehicle 8",
    price: "960755",
    drive: "all",
    availability: "true",
    power: "170",
    country: "Russia",
  },
  vehicle9: {
    name: "Vehicle 9",
    price: "1666666",
    drive: "rear",
    availability: "true",
    power: "235",
    country: "Germany",
  },
  vehicle10: {
    name: "Vehicle 10",
    price: "120753",
    drive: "front",
    availability: "true",
    power: "167",
    country: "China",
  },
  vehicle11: {
    name: "Vehicle 11",
    price: "460798",
    drive: "rear",
    availability: "true",
    power: "85",
    country: "Russia",
  },
  vehicle12: {
    name: "Vehicle 12",
    price: "1999999",
    drive: "all",
    availability: "true",
    power: "300",
    country: "Germany",
  },
};

export { quadbikes, launch, jetskis, boats, vehicles };
